#!/bin/bash

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey

# startxfce4  &
# mate-session &
export XKL_XMODMAP_DISABLE=1
/etc/X11/Xsession /usr/bin/startxfce4
